version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
        environment:
          ENV: CI
    steps:
      - checkout
      - run:
        name: Installing dependencies
        command: |
          cd ~/web
          pip install -r requirements/test.txt
          pip install -r requirements/prod.txt
  test:
    steps:
      - run:
        name: Run tests and coverage
        command: |
          pytest .

  deploy:
    steps:
      - run:
        name: Heroku deployment
        command: |
          heroku push origin master
workflows:
    version: 2
    build_test_deploy:
      jobs:
        - build:
        - test
          requires:
            - build
        - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
